events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        default_type text/plain;
        access_log off;
        error_log /dev/null;
        return 404 "404 Not Found\n";
    }
}
